### ISSUE TITLE
The data couldn’t be read because it isn’t in the correct format.

### ISSUE THREAD

**Issue by kiliankoe** [RobotsAndPencils/xcodes#105]
On trying to `update` I'm unfortunately only seeing this error. Could it be that Apple has changed the response xcodes is awaiting here?

```
> xcodes update
The data couldn’t be read because it isn’t in the correct format.
The data couldn’t be read because it isn’t in the correct format.
```

Huge thanks for xcodes btw, it has made my life so much easier through these last few weeks of betas ❤️

**Comment by interstateone** [comment]
Thanks for opening this issue @kiliankoe, and sorry you're hitting this problem. I've seen it mentioned a few times now, and for some reason I can't seem to ever reproduce it myself. If you're able to provide some more information about how it's failing with something like an HTTP proxy that would be really helpful (sanitize anything secret from requests and responses.) One time I helped a colleague set one up and xcodes immediately started working again (🤷‍♂️), but maybe this will work for you.

Longer term this error message should be improved, and perhaps xcodes should have a verbosity flag or something to help with debugging.

**Comment by kiliankoe** [comment]
Argh, I just wanted to capture some requests through Proxyman and everything worked again. But good to know that this is a known but elusive bug already, I'll keep an eye out and try and capture more data as soon as it appears again. 

FWIW I also immediately tried running`xcodes update -v` in the hope of seeing more information that way 😅 

Feel free to close this issue if you're already tracking this elsewhere 😊

**Comment by bonkey** [comment]
I reported similar on #96 and it still does not work for me. I was wondering, perhaps it's a VPN/network issue? Like we had some time ago a problem with uploading apps to App Store Connect and had to switch to HTTP: `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t HTTP"`

**Comment by interstateone** [comment]
@kiliankoe I'm wondering if you've seen this issue again since the SMS 2FA changes in version 0.12.0?

**Comment by kiliankoe** [comment]
I have not had this issue reappear so far 🙌

**Comment by FrankVilla** [comment]
Everything was working a few hours ago and now  The data couldn’t be read because it isn’t in the correct format.
without having changed anything
