### ISSUE TITLE
Xcode-Beta.app -> Xcode-beta.app ?

### ISSUE THREAD

**Issue by krzyzanowskim** [RobotsAndPencils/xcodes#108]
Shouldn't it check for `Xcode-beta.app` instead `Xcode-Beta.app` when moves bundle? 

https://github.com/RobotsAndPencils/xcodes/blob/8d9897cfab203348bfab9a1fc58e7553aee40510/Sources/XcodesKit/XcodeInstaller.swift#L529

**Comment by interstateone** [comment]
😅 Yep, it looks like you're correct. I'm not sure why Beta is capitalized there. I wonder if this just happened to work if users had a (default) case-insensitive filesystem. Would you like to open a PR with that change?
