### ISSUE TITLE
Find arai2c in PATH instead of /usr/bin/local

### ISSUE THREAD

**Issue by interstateone** [RobotsAndPencils/xcodes#118]
This being hard-coded works for now, but it would work for more users (without providing a path) if it looked in PATH, and Homebrew is going to change to use `/opt/homebrew` as its prefix (https://github.com/Homebrew/brew/issues/7857) at some point in the future.

**Comment by cooljeanius** [comment]
also other package managers have aria2 available, too; I have it installed via MacPorts, for example
