### ISSUE TITLE
macOS User Password

### ISSUE THREAD

**Issue by menvol3** [RobotsAndPencils/xcodes#128]
Hi, I’m trying to automate Xcode installation with this tool, and I’d like to now is it possible to add variable "macOS User Password" or maybe checking if user have sudo rights and then ask for the password prompt or execute command ?

**Comment by interstateone** [comment]
Hey @menvol3, good question. The short answer is that there isn't anything like that right now, and xcodes could probably handle automation use cases better. Can you tell me more about what you're trying to do and how you're doing it? Please elaborate as much as you can, but include how xcodes is being invoked (for example from a shell script) and whether its in an interactive shell. Then we can figure out the best way to handle this.

**Comment by menvol3** [comment]
Hi @interstateone 
Currently I’m trying to create Jenkins job that will be installing/updating Xcode on machines with this tool.
For now it invoked from shell command `xcodes install 12`. Env variables xcodes login and password also exists in this pipeline.
it will be good if the same variable as login or pass, will be for the mac os user password too.
