### ISSUE TITLE
Generating zsh completion script not working, --generate-completion-script not recignised

### ISSUE THREAD

**Issue by peterfriese** [RobotsAndPencils/xcodes#132]
When running `xcodes --generate-completion-script`, the output is not the completion script (as expected), but rather the following error message:

```bash
❯ xcodes version
0.15.0
❯ xcodes --generate-completion-script
Error: unknown shorthand flag: 'generate-completion-script'
Usage:
  xcodes [flags]
  xcodes [command]

Available Commands:
  download   Download a specific version of Xcode
  install    Download and install a specific version of Xcode
  installed  List the versions of Xcode that are installed
  list       List all versions of Xcode that are available to install
  select     Change the selected Xcode
  uninstall  Uninstall a specific version of Xcode
  update     Update the list of available versions of Xcode
  version    Print the version number of xcodes itself

Flags:
      --directory string  The directory where your Xcodes are installed. Defaults to /Applications.

Use "xcodes [command] --help" for more information about a command.

unknown shorthand flag: 'generate-completion-script'
exit status 255
```

**Comment by interstateone** [comment]
Hi @peterfriese! Thanks for opening this issue. I was able to reproduce it shortly after you opened it, and still can with the 0.15.0 release, but I can't reproduce it on `main` or the latest 0.16.0 release. Can you try updating to 0.16.0 and let me know if you still have this issue?

**Comment by peterfriese** [comment]
Can confirm this is now working with xcodes 0.16.

As a side note, I had to add `autoload -Uz compinit && compinit` to my `.zshrc` to turn on completion (which I found a bit surprising, I'd have thought command completion was turned on by default in zsh.
