### ISSUE TITLE
Add signout command

### ISSUE THREAD

**Issue by interstateone** [RobotsAndPencils/xcodes#136]
Add a signout command so that users can more easily sign out or switch accounts. Currently the latter requires using the `XCODES_USERNAME` environment variable which is not very discoverable.

- [x] Remove all Keychain items
- [x] Remove cookies in the shared URLSession
- [x] Set `defaultUsername` in Configuration to nil
- [x] If #130 has merged, use coloured output for success, warning or failure messages

**Comment by evgeniyd** [comment]
Hey. Just wonder, is there any plan to release the version with this change? 
Building from source indeed works for me, but seeing the feature as an official release would streamline the process.

Thanks.
