### ISSUE TITLE
Don't exit(1) on certain errors, when they're not true failures. 

### ISSUE THREAD

**Issue by tahirmt** [RobotsAndPencils/xcodes#142]
Currently if I run `xcodes install --latest` the command fails if Xcode is already installed. Since it is already installed, do not fail the command

**Comment by tahirmt** [comment]
@MattKiazyk Yes I see this but it exists after and doesn't continue. I have `xcodes` as part of a script that has other steps after this but xcodes exits my script because Xcode is already installed

**Comment by MattKiazyk** [comment]
Ah I see what you're meaning. Thanks for that. For sure we shouldn't be exiting hard in this scenario.

**Comment by julianxhokaxhiu** [comment]
I recently crossed exactly this issue and I was wondering if some progress have been done related.

In my own case this is the error:
```sh
$ xcodes install 12.4
12.4 is already installed at /Applications/Xcode-12.4.0.app
make: *** [Makefile:50: install_xcode_versions] Error 1
```

I could bypass this by adding `|| true` at the moment, but I would be nice if you could maybe not exit with an error code > 0.

Thank you in advance!
