### ISSUE TITLE
Question: Location of temporary Xcode download

### ISSUE THREAD

**Issue by hansemannn** [RobotsAndPencils/xcodes#147]
I started a new Xcode download and forgot about the progress, so I closed the Terminal. It seems like the half-baked Xcode now still takes some GB's of space, but I'm not sure where to search for it. Does someone know more here?

I found `~/Library/Application Support/com.robotsandpencils.xcodes` already, but it's not there.

**Comment by MattKiazyk** [comment]
Hi Hans,

That's where it will be when xcodes is set up to use aria2 (which it is by default). If you see no .xip or anything large in that directory you indicated, it most likely will be in the MacOS temporary directory somewhere.

Have you tried rebooting to clean up the temporary/cache directories?

**Comment by hansemannn** [comment]
Hi Matt,

I tried both, bu it's still sitting somewhere…As I notice, this will be hard to solve from outside, so I think it's okay to close this.

**Comment by MattKiazyk** [comment]
Sounds good.

My only other suggestion would be in `Storage Management` app on your Mac. I'm sure if there's a 10 Gb file it _should_ show you, you would think
