### ISSUE TITLE
macOS Catalina 10.15 support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [RobotsAndPencils/xcodes#150]
Hi,

I've found this tool and I would like to start using it to maintain various XCode installations in parallel. Although I noticed this requires Big Sur. Is there a particular reason for it? Could it "downgraded" to support at least Catalina?

Thank you very much in advance,
Julian

**Comment by MattKiazyk** [comment]
Hi @julianxhokaxhiu 

Xcodes doesn't have a requirement for Big Sur. Is there something you are seeing that is resulting in errors? 

Thanks

**Comment by julianxhokaxhiu** [comment]
Hi,

Thanks for the reply. Apparently I think there's some confusion in the Homebrew community.

I was trying to install and use xcodes through `brew`, which itself [sets the requirement to Big Sur](https://formulae.brew.sh/cask/xcodes#default). It could be they inherited this requirement because [of the notice](https://github.com/RobotsAndPencils/XcodesApp#installation) in the `.app` version of this project.

Can you please confirm this project can run on Catalina? Just to have an argument when I'll open an issue on the brew side.

Thank you in advance,
Julian
