### ISSUE TITLE
Enhancement: Add Xcode release date to info pane in Xcodes.app

### ISSUE THREAD

**Issue by provTheodoreNewell** [RobotsAndPencils/xcodes#152]
I noticed there isn't a clear indication of release date for each Xcode version that I could find in Xcodes.app. I think it would be useful to appear in the info pane when selecting a specific version.

I'm not sure if it's meant to already be visible (in which case this might be a bug), although I see it should be possible to retrieve (at least when using the [Xcode Releases](https://xcodereleases.com) data source).

Environment: 
Xcodes.app 1.1.0 (7)
macOS 11.4
Data source: Xcode Releases

**Comment by provTheodoreNewell** [comment]
I'm hoping to work on this, time allowing.

**Comment by MattKiazyk** [comment]
Hey @provTheodoreNewell - Can you add this to the Xcodes.app repo - https://github.com/RobotsAndPencils/XcodesApp/issues instead of this one? This is for the CLI version. 

I'm going to close this issue as it's relevant to Xcodes.app not Xcodes

**Comment by provTheodoreNewell** [comment]
Added to Xcodes.app repo: https://github.com/RobotsAndPencils/XcodesApp/issues/145
