### ISSUE TITLE
Xcode 13 Beta 5 missing

### ISSUE THREAD

**Issue by pro-sumer** [RobotsAndPencils/xcodes#153]
Today's Xcode 13 Beta 5 is missing (after running `xcodes update`).

Is this a bug? Or should I be more patient? (because you need to manually add releases?)

**Comment by pro-sumer** [comment]
Oh: https://twitter.com/XcodeReleases/status/1425162386420363269

**Comment by unnamedd** [comment]
It is already available in the list:
```
13.0 Beta (13A5154h)
13.0 Beta 2 (13A5155e)
13.0 Beta 3 (13A5192i)
13.0 Beta 3 (13A5192j)
13.0 Beta 4 (13A5201i)
13.0 Beta 5 (13A5212g) (Installed, Selected)
```

**Comment by pro-sumer** [comment]
Works fine now. Thanks!
