### ISSUE TITLE
Cannot find version 13.0

### ISSUE THREAD

**Issue by MarcSteven** [RobotsAndPencils/xcodes#156]
I want to install the latest version about the Xcode , I also installed Xcodes completely, and then run the command line as below:
`xcodes install 13.0`

and then it showed cannot find the version of 13

**Comment by MattKiazyk** [comment]
Hi @MarcSteven 

Does `13.0` show up when you type `xcodes list` ? If not does `xcodes update` show it? 

Secondly `13.0 RC` and `13.0` are the same build, so you have `13.0 RC` installed, you can simply rename the app to `Xcode-13.0.0` and xcodes will see it.

Let me know if any of those options work for you?

**Comment by iRILLLL** [comment]
does this work for you?
```
xcodes update --data-source=apple
```

**Comment by MarcSteven** [comment]
> Hi @MarcSteven 
> 
> 
> 
> Does `13.0` show up when you type `xcodes list` ? If not does `xcodes update` show it? 
> It do
it cannot do because it has errors-The operation could not be completed.
> ![image](https://user-images.githubusercontent.com/13824297/136176254-34ea3fb8-2e8a-4fc9-bf32-f218074654aa.jpeg)
> 
> Secondly `13.0 RC` and `13.0` are the same build, so you have `13.0 RC` installed, you can simply rename the app to `Xcode-13.0.0` and xcodes will see it.
> 
> 
> 
> Let me know if any of those options work for you?

All is not okay to solve the problem.

**Comment by MarcSteven** [comment]
> does this work for you?
> 
> ```
> xcodes update --data-source=apple
> ```

It's not okay to solve the issue


`The operation couldn’t be completed. (DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))))
The operation couldn’t be completed. (DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))))`

**Comment by thepoppingone** [comment]
It works now, I even downloaded Xcode 13.1 from it, you might want to close this!

**Comment by MarcSteven** [comment]
But actually it cannot be okay

**Comment by MattKiazyk** [comment]
Closing this as all the error message was a result of different scenarios with apple accounts. With 1.0 we no longer require that
