### ISSUE TITLE
[Feature Request] xcodes install *** --select

### ISSUE THREAD

**Issue by ChaseFlorell** [RobotsAndPencils/xcodes#161]
Whenever I install a new version of xcode, I always want to select it at the same time. It'd be great if we could combine the `select` with the install.

```bash
> xcodes install 13.1 --select
# or
> xcodes install --latest --select
```

**Comment by julianxhokaxhiu** [comment]
I agree, this would be a very nice handy feature. I wonder why it's not there already.

**Comment by jokerputihboy** [comment]
Boy99
