### ISSUE TITLE
Verbose mode

### ISSUE THREAD

**Issue by fishcharlie** [RobotsAndPencils/xcodes#162]
It would be great to have a verbose mode that shows if `aria2` is being used or not. I don't see that large of a performance difference after installing it. So I'm curious if it is indeed using `aria2` or if there is something wrong on my end.

**Comment by MattKiazyk** [comment]
I'm going to close this one as we currently show a `"Downloading with urlSession - for faster downloads install aria2 (`brew install aria2``  if you aren't using `aria2`
