### ISSUE TITLE
`Beta 1` shown as `Beta` in list

### ISSUE THREAD

**Issue by fishcharlie** [RobotsAndPencils/xcodes#164]
For Beta 1 versions the list shows it as Beta, and cuts off the 1. Is this a bug or intentional?

**Comment by fishcharlie** [comment]
@MattKiazyk Any thoughts on this? Just got reminded of this since Xcode 13.3 Beta 1 was released. Is this intentional or a bug?

**Comment by MattKiazyk** [comment]
@fishcharlie It's intentional.. I'm not stuck to it, but in my opinion it reads better. Seems to be pretty common first betas have no marketing number while future betas add numbers.

**Comment by fishcharlie** [comment]
@MattKiazyk Got it. I'm going to close this issue then. It's something I can fix on my end if I decide it's worth it.
