### ISSUE TITLE
Error: `Could not find version 13.2 Release Candidate.`

### ISSUE THREAD

**Issue by fishcharlie** [RobotsAndPencils/xcodes#167]
I'm trying to run: `xcodes download 13.2 Release Candidate`. But I get an error: `Could not find version 13.2 Release Candidate.`.

However when running `xcodes list`, it does show `13.2 Release Candidate (13C90)` at the bottom of the list.

**Comment by MattKiazyk** [comment]
Hi @fishcharlie 

My apologies on this one. There's an outstanding issue with Release Candidates/Betas that xcodes has trouble with to determine what to download. In the meantime, you can use 

`xcodes install --latest-prerelease` 

to install 13.2 RC in the meantime.

**Comment by fishcharlie** [comment]
@MattKiazyk Got it. Wanting to download and not install.

I have it setup as a cron job to automatically check for new versions of Xcode and download them using this tool. So changing the command won’t really help with my use case.

I might try to find some free time and dig into the code to see if I can come up with a solution and submit a PR.

**Comment by fishcharlie** [comment]
@MattKiazyk I submitted a PR for this! If there is anything I can do to help get this merged and get a new release please let me know. Thanks so much!!!

**Comment by MattKiazyk** [comment]
@fishcharlie released a `v0.18.0` - which should have your change in.. thanks!
