### ISSUE TITLE
Change the Apple ID Associated with Xcodes

### ISSUE THREAD

**Issue by AndyIbanez** [RobotsAndPencils/xcodes#169]
Hey all,

Sorry for making an issue for this, but I can't figure out how to change my Apple ID. I recently changed the email linked to my Apple ID and I'm trying to use Install some Xcode versions, but I can't do that unless I login. The prompt only shows me the old Apple ID. I checked the keychain to see if there were any entries where the tool was grabbing it from but I found nothing. Typing `xcodes` as a solo command doesn't give me anything I could use for this.

The documentation mentions a `xcodes signout` command, but it doesn't appear to be implemented yet (despite the source code saying otherwise, the error I'm getting is `Error: Unexpected argument 'signout'`). I'm running version 0.17.0

How can I change the Apple ID that Xcodes is using?

**Comment by MattKiazyk** [comment]
Hi @AndyIbanez 

Can you update xcodes? Just released a version today that has that `signout` command. That _should_ help you sign out fully.

If not, let me know.

Thanks

**Comment by AndyIbanez** [comment]
@MattKiazyk the command is there now, but when I login it still prompts for the same Apple ID I just logged out from.

**Comment by MattKiazyk** [comment]
Hey @AndyIbanez sorry about your troubles

If you called the `signout` command and it's skipping the`Apple ID` prompt

![image](https://user-images.githubusercontent.com/1119565/146487483-fb8fced4-0fe1-4f11-ba82-e257cc90763d.png)

Then that will be loading the username from `XCODES_USERNAME` Environment variable. After a `signout` it should prompt for a new apple id first unless the environment variable is there (or there's a bug somewhere)

**Comment by AndyIbanez** [comment]
Ahh gotcha, I forgot I set a temporary env variable for `XCODE_USER` as a workaround to not being able to sign out before 0.18.0.

My mistake. Sorry about that!
