### ISSUE TITLE
Support arm64 (M1) builds

### ISSUE THREAD

**Issue by fishcharlie** [RobotsAndPencils/xcodes#170]
When trying to install the latest version of xcodes through Homebrew the binary it installs is only for arm64.

This means xcodes no longer runs on Intel based Macs.

This seems to be an isolated issue to v0.18.0.

cc/ @MattKiazyk

**Comment by MattKiazyk** [comment]
💩

I built 0.18.0 on an M1. I'll go back to intel and release a new version. I'll keep this ticket open to make it buildable with an m1 and be universal.

**Comment by MattKiazyk** [comment]
@fishcharlie - sorry about that - 0.19.0 is out now

**Comment by fishcharlie** [comment]
@MattKiazyk Why was this closed? I thought it was going to be kept open to make it buildable with M1 and be a universal binary?
