### ISSUE TITLE
bad CPU type in executable: xcodes

### ISSUE THREAD

**Issue by wiencheck** [RobotsAndPencils/xcodes#171]
I installed `xcodes` via HomeBrew on my MacBook Pro, x86 running macOS 11.6

Whenever I'm trying to use `xcodes` I'm getting the error 

`zsh: bad CPU type in executable: xcodes`

How can I fix it? Is this utility only for ARM processors?

**Comment by MattKiazyk** [comment]
hi @wiencheck 

0.18.0 was released that had that issue. Ive subsequently released 0.19.0 which should fix your issue.

Thanks
