### ISSUE TITLE
Unable to install Xcode

### ISSUE THREAD

**Issue by jaceklyp** [RobotsAndPencils/xcodes#175]
I downloaded the latest standalone version of Xcodes and I'm unable to download any version of the Xcode.
Whenever I tap on the "Install" button the following dialog appears:

![xcodes](https://user-images.githubusercontent.com/1254128/147940531-3d72b468-7cf0-4d68-b9d7-f974a9fba1c2.png)

I'm running it on the M1Pro.
I've rebooted the mac couple of times and reinstalled the app but it didn't help.
Changing data source or downloader didn't help neither.

Thanks for any help.

**Comment by MattKiazyk** [comment]
Hi @jaceklyp - this looks like an Xcodes.app issue not the Xcodes CLI which this repo is.

You'll see similar issues there -  https://github.com/RobotsAndPencils/XcodesApp/issues/173

**Comment by jaceklyp** [comment]
Thanks @MattKiazyk, my bad! Closing it here.
