### ISSUE TITLE
Update command is not working ?

### ISSUE THREAD

**Issue by leavesster** [RobotsAndPencils/xcodes#194]
How could I update installed version?

I only install one Xcode which is default one not installed by `xcodes`

```shell
➜  ~ xcodes installed
11.2 (11B52) (Selected) /Applications/Xcode.app
```

```shell
xcodes update --directory /Applications/Xcode.app
# or
xcodes update --directory /Applications

# I also try 
➜  ~ xcodes update --directory /Applications 11.7
# it return
Error: Unexpected argument '11.7'
Usage: xcodes update [--directory <directory>] [--data-source <data-source>] [--color] [--no-color]
  See 'xcodes update --help' for more information.
```
It just output xcodes list then finish command without anything.

the `xcodes update` seems every thing is options, but maybe the help has some wrong ?
It doesn't even need an upgrade version number……

`xcodes update [--directory <directory>] [--data-source <data-source>] [--color] [--no-color]`

## Info

```shell
➜  ~ xcodes version
0.20.0
```
MacOS version: 10.14.6

Maybe my MacOS's version is too low?
But I think maybe we still need some working well  `update` command example .

**Comment by MattKiazyk** [comment]
@leavesster sorry you're having trouble. What are you trying to do? 

`xcodes update` will simply update the Xcode list from Apple's servers. It won't install anything.

If you're wanting to install a specific Xcode version, you can use `xcode install 13.3.1` where you can type in the version you want. By default the `--directory` path will be `/Applications` so you don't have to send that in.

Let me know if that makes more sense? With your lower Mac OS version, it should work, but the newer Xcode versions will not.

**Comment by leavesster** [comment]
Thanks for such a quick reply.

I want to know a `update` command example, so that I have a way to find out why I can't get it to work.
`xcodes update` seems not do anything at my case.

From you comment, I now know why …… 
it seems  the `xcodes update` just update the result `xcodes list`, not update the xcode we selected.
It quite strong that it need a directory ……

Thank you for your reply
