### ISSUE TITLE
Can not install the privileged helper

### ISSUE THREAD

**Issue by patrick-fu** [RobotsAndPencils/xcodes#195]
I install the Xcodes app via homebrew, and the Xcodes version is 1.4.0 (12)

After the Xcode installed , it failed in the step of switch Xcode version. 

<img width="791" alt="Screenshot 2022-04-24 at 19 14 09" src="https://user-images.githubusercontent.com/20736775/164973731-9d7ee9f4-c4ed-48bf-ac99-088b0634fb53.png">
<img width="791" alt="Screenshot 2022-04-24 at 19 14 16" src="https://user-images.githubusercontent.com/20736775/164973734-809edf2e-f6d4-475b-9ea6-ff22416bb56d.png">

**Comment by MattKiazyk** [comment]
Hi @patrick-fu can you post this on the https://github.com/RobotsAndPencils/XcodesApp repo instead. This repo is for the CLI version. Thanks

**Comment by patrick-fu** [comment]
Sorry i didn't notice this, already post to the XcodesApp repo
https://github.com/RobotsAndPencils/XcodesApp/issues/213
