### ISSUE TITLE
Can we not set XCODE_USER and XCODE_PASSWORD?

### ISSUE THREAD

**Issue by aelam** [RobotsAndPencils/xcodes#198]
I see the username and password are saved in keychain
can xcodes just access them from keychain without XCODE_USER and XCODE_PASSWORD environment variables?

**Comment by MattKiazyk** [comment]
hi @aelam

For sure - just don't set those environment variables `XCODES_USERNAME`/`XCODES_PASSWORD` and it'll look for them in the keychain

You'll see here it looks for the environment variable first, then goes to the keychain. 

https://github.com/RobotsAndPencils/xcodes/blob/main/Sources/XcodesKit/XcodeInstaller.swift#L433
