### ISSUE TITLE
Installing Xcode 13.4.1 fails with ProcessExecutionError

### ISSUE THREAD

**Issue by tkafka** [RobotsAndPencils/xcodes#203]
Any advice? This happens right after I tap the install button, other Xcode versions install fine.

```
Unable to install Xcode
The operation couldn’t be completed. (ProcessExecutionError(process: <NSConcreteTask: 0x6000018fc550>, standardOutput: "", standardError: ""))
```

![Screenshot 2022-06-07 at 9 26 20](https://user-images.githubusercontent.com/876717/172321075-8d105546-5bc5-4853-ac5a-af0c45eaa0c4.png)

**Comment by martin-braun** [comment]
Same problem with 14.1. Did Apple change something on their end?

**Comment by MattKiazyk** [comment]
Closing as these belong on the https://github.com/RobotsAndPencils/XcodesApp repo. 

A new version of the CLI was released yesterday that fixed Apple blocking an endpoint. The fix is merged in, but a new version hasn't been released just yet.
