### ISSUE TITLE
Feature Request: Options for managing simulator runtimes

### ISSUE THREAD

**Issue by jonbrooks** [RobotsAndPencils/xcodes#213]
This may be considered out of scope for this tool, but starting in XCode 14, apps that require other simulator runtimes (like `tvOS` or `watchOS`) must do [additional steps](https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes) before XCode is functional. It would be awesome if `xcodes` could handle some of these use cases, perhaps through command line options for installing additional runtimes.

**Comment by MattKiazyk** [comment]
Hey @jonbrooks definitely will make this a higher priority. Especially downloading the large files with aria2 should help a ton there. 

Thanks for the suggestion

**Comment by MattKiazyk** [comment]
@jonbrooks I'm going to close this issue in favor of the #91
