### ISSUE TITLE
`xcodes download` does not find version

### ISSUE THREAD

**Issue by finestructure** [RobotsAndPencils/xcodes#216]
I'm not sure if I'm perhaps missing something blindingly obvious but I can't manage to download any Xcode releases via `xcodes download`:

```
❯ xcodes version
1.0.0
~
❯ xcodes download 13.2.1
Could not find version 13.2.1.
~
❯ xcodes download 14
Could not find version 14.0.
~
❯ xcodes download 14.0.0
Could not find version 14.0.
~
❯ xcodes download 13.2.1 --directory ~/Downloads
Could not find version 13.2.1.
~
❯ xcodes download 13.2.1 --data-source apple
Could not find version 13.2.1.
❯ xcodes download 13.2.1 --data-source xcodeReleases
Could not find version 13.2.1.
~
```

Is it me or is it `xcodes`? 😅

Xcodes.app works just find and I'm loving it, but since I have bad and metered internet, I need to hold on to the xips in order to install them across several machines and vms. (AFAICT, Xcodes.app doesn't leave the xip around when it's done so I can't really use it until my connection situation improves.)

**Comment by MattKiazyk** [comment]
Hi @finestructure 

How did you get 1.0? Did you grab from main? 

What happens if you Xcodes list or Xcodes update first?

Thanks

**Comment by MattKiazyk** [comment]
Secondly. Xcodes.app will trash the xip leaving it in the trash bin which you can then move to where you need it to.

**Comment by finestructure** [comment]
> Secondly. Xcodes.app will trash the xip leaving it in the trash bin which you can then move to where you need it to.

Oh, that's great to know, I never thought to check. Thanks!

> How did you get 1.0? Did you grab from main?

I installed via mint. As far as I can tell that grabs the 1.0 tag.

> What happens if you Xcodes list or Xcodes update first?

That lists the versions just fine:

```
❯ xcodes list
...
12.0 Beta 2
12.0 Beta 3
12.0 Beta 4
12.0
12.0.1
12.1
12.2 Beta
12.2 Beta 2
12.2 Beta 3
12.1.1 Release Candidate
12.2 Release Candidate
12.2
12.3 Beta (12C5020f)
13.1 (13A1030d) (Installed)
13.2.1 (13C100) (Installed)
13.3.1 (13E500a) (Installed)
13.4.1 (13F100) (Installed)
14.0 Beta 6 (14A5294g) (Installed)
14.0 (14A309) (Installed, Selected)
❯ xcodes download 13.2.1
Could not find version 13.2.1.
```

Oooh, I see what's happening. It's because I've already got it on this machine. I was looking for an easy way to re-download it to install it in a VM. Copying Xcode.app over is often slow and unreliable.

I can probably just move the installed version away to be able to trick `xcodes` into re-downloading, although it'd be nice if that was an option without.

I'll close this then - thanks for your help!
