### ISSUE TITLE
Improve pre-release version comparison

### ISSUE THREAD

**Issue by interstateone** [RobotsAndPencils/xcodes#22]
See release [0.3.1](https://github.com/interstateone/xcodes/releases/tag/0.3.1) and acd05f937fe9f79afa71c936643396b63f9ded81. Ideally the output of `xcodes installed` and `xcodes list` would be more precise to reflect the installed and available pre-release versions. Need to check if there's enough info available before downloading a pre-release version and in an installed Info.plist to do this.

Pre-release builds publish a product version on developer.apple.com/downloads, e.g. Xcode 11 Beta 1 is `11M336W`. The app bundle contains a file at Contents/version.plist and the value for ProductBuildVersion matches this, although it should be compared case-insensitively because it is `11M336w`.

**Comment by paulthorsteinson** [comment]
I was about to open an issue but this seems linked to what I was seeing.  I had installed Xcode 11 beta 1 and then when I ran xcodes I got `11.0.0-beta.2 (Installed)` even though it was beta 1 that was installed.
