### ISSUE TITLE
Question: About sudo process migration

### ISSUE THREAD

**Issue by noppefoxwolf** [RobotsAndPencils/xcodes#224]
Hi, I'm interested in having [PAM](https://en.wikipedia.org/wiki/Pluggable_authentication_module) available in xcodes.
I'll try to make a PR, but I have a few questions before it.

1. Are there any concerns about using `posix_spawn` instead of `Process` when running sudo?
2. Is it OK to obsolete `readSecureLine`?

I would like to do the migration without interfering with the current use case.

Thanks

**Comment by noppefoxwolf** [comment]
By becoming sudo via PAM, you can do away with your own password input and use a user-specified method (ex. Touch ID).

**Comment by MattKiazyk** [comment]
Hi @noppefoxwolf always open for ways to make Xcodes better!

1. From what I read and my understanding, there is no current concerns with using `posix_spawn` 
2. I'm not too familiar with PAM but Xcode CLI can be used in CI environments so as long as there are options to keep the existing functionality (manually type in sudo password security) i'm up to see how it can be improved.

**Comment by noppefoxwolf** [comment]
@MattKiazyk 
Thank you for feedback!

> I'm not too familiar with PAM but Xcode CLI can be used in CI environments so as long as there are options to keep the existing functionality (manually type in sudo password security) i'm up to see how it can be improved.

OK, I wasn't thinking about CI.
I'd like to keep the current behavior and provide the option to use PAM.
