### ISSUE TITLE
Running xcodes install with sudo fails with "Could not find version"

### ISSUE THREAD

**Issue by akselilukkarila** [RobotsAndPencils/xcodes#225]
I am migrating from `xcode-install` / `xcversion` to this tool, which we use to automate installing Xcode in CI.

Trying to run `sudo xcodes install <version>` seems to always fail with `Could not find version <version>`

For example:
```
➜  ~ sudo xcodes install "14.0.1"
Password:
Could not find version 14.0.1.

➜  ~ xcodes install "14.0.1"

Downloading with aria2
```
Same thing happens with version 14.0 as well.

The version is there for sure, I have run `xcodes update` and added a check: 
```
➜  ~ xcodes list | grep 14.0
14.0 Beta (14A5228q)
14.0 Beta 2 (14A5229c)
14.0 Beta 3 (14A5270f)
14.0 Beta 4 (14A5284g)
14.0 Beta 5 (14A5294e)
14.0 Beta 6 (14A5294g)
14.0 (14A309) (Installed, Selected)
14.0.1 (14A400)
```

I need to run it with sudo since the install requires the user credentials according to the documentation, and this is running in CI in a non-interactive shell.

**Comment by MattKiazyk** [comment]
@akselilukkarila Can you `sudo xcodes update` first? 

Believe the `sudo` makes it save the list somewhere else.

**Comment by akselilukkarila** [comment]
> @akselilukkarila Can you `sudo xcodes update` first?
> 
> Believe the `sudo` makes it save the list somewhere else.

Thanks, running `sudo xcodes update` first works 👍🏻  Maybe this could be mentioned in the documentation

**Comment by rpendleton** [comment]
This is actually a recent regression in 1.0.0, and my PR for #226 should fix the issue so that the update isn't required.
