### ISSUE TITLE
xcode install does not work without xcodes list

### ISSUE THREAD

**Issue by vandrham** [RobotsAndPencils/xcodes#231]
After a clean first install of xcodes using homebrew, I am trying to install a specific version of xcode:

```xcodes install 13.4.1```

This command fails with the message "Could not find version 13.4.1".
To solve this, I first have to do ```xcodes list```
It seems like the list with available versions is only updated when explicitly issuing the list command

**Comment by MattKiazyk** [comment]
This should be fixed up next build with https://github.com/RobotsAndPencils/xcodes/pull/226 merge. If it's an old list, it will update itself first.
