### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by lordzsolt** [RobotsAndPencils/xcodes#243]
When I try to download any version:
- it downloads about 100KBs of it
- considers it 100%
- then fails with the error: `The archive "Xcode-14.0.0+14A309.xip" is damaged and can't be expanded.`

I have tried both with the CLI and the Xcodes app. 
(Both of them were installed through Homebrew)

When I run it from the CLI, I see the following output:

```
xcodes install --latest --experimental-unxip
Updating...
Latest non-prerelease version available is 14.1

Downloading with aria2

(2/6) Unarchiving Xcode (This can take a while)
Using experimental unxip. If you encounter any issues, remove the flag and try again
zsh: trace trap  xcodes install --latest --experimental-unxip
```

I presume the last line is the issue?

EDIT:
- I have tried with and without aria2
- I have tried with and without `--experimental-unxip`
- I have tried multiple Xcode versions

**Comment by lordzsolt** [comment]
Is there anything I can do to authenticate?

I have logged in the Xcodes app before pressing `Install`, and it still produced the same output.

**Comment by MattKiazyk** [comment]
@sebsto @lordzsolt @michaeleisel What are your Mac OS's? 

These errors _seem_ to be all Ventura

**Comment by cltnschlosser** [comment]
Seeing it now on 12.6.1. 2020 M1 mac mini

**Comment by cltnschlosser** [comment]
It could be an apple issue because `xcode-select --install` was also giving me issues.

**Comment by lordzsolt** [comment]
@MattKiazyk Yup, Ventura 13.0.1

**Comment by lordzsolt** [comment]
> It could be an apple issue because `xcode-select --install` was also giving me issues.

No issues with `xcode-select --install` on my side (besides it being awfully slow)

**Comment by michaeleisel** [comment]
I'm on 12.6

**Comment by MattKiazyk** [comment]
It's looking like Apple changed something so I now can't get a token the way I was to download. I'm looking into it.

**Comment by MattKiazyk** [comment]
Workaround (unfortunately) at the moment is
```
xcodes update --data-source apple
xcodes install 14.0.1 --data-source apple
```
which will use the original way of Apple creds to get the token in order to download. 

Sorry everybody, looks like Apple may have stopped our new way of getting a token 😢

**Comment by vilanovi** [comment]
I use xcodes 1.5.0 and it's working. However, on version 1.8.0 we are having the issue.

**Comment by rogerluan** [comment]
I really hope this is just a temporary issue on Apple's end 😬 Being forced to authenticate to download Xcode is just terrible 😞 

I will check with my network to see if anyone has any insight within Apple so we know whether this is a temporary issue or a permanent change they made intentionally 🙏

**Comment by sebsto** [comment]
I think the authless download was unintentional in the first place. They just fixed a bug this week

**Comment by MattKiazyk** [comment]
Xcodes 1.2 was released tonight - It adds back the requirement of apple login for xcodereleases data source.
