### ISSUE TITLE
Additional --path option for xcodes runtimes install command

### ISSUE THREAD

**Issue by martinknabbe** [RobotsAndPencils/xcodes#256]
It would be beneficial and faster for us to download the runtime files from our own mirror. Similar to the `xcodes install` command the `xcodes runtimes install` command could get a `--path` option to specify the local path of the downloaded dmg file.
```
$ xcodes runtimes install 'iOS 15.0' --path '/Downloads/iOS15.dmg'
```
This would execute the same steps as the existing command with the difference of skipping the download and installing from a local file.

**Comment by amosolgo-lutron** [comment]
There is an existing option which might meet your needs. Excerpt from `xcodes runtimes install --help`

`  --directory <directory> The directory to download the runtime archive to. Defaults to ~/Downloads.`

The catch is that the dmg filename needs to match the default name for the image. In other words, your mirror needs to use the same filenames as Apple. In the case of iOS 15.0, I think that would be `com.apple.pkg.iPhoneSimulatorSDK15_0-15.0.1.1633542405.dmg`.

**Comment by martinknabbe** [comment]
Thanks for the hint. That works for us. I'm going to close the issue.
