### ISSUE TITLE
Download xcode from GCS

### ISSUE THREAD

**Issue by lanycrost** [RobotsAndPencils/xcodes#270]
I don't know who is the owner of this bucket, but here you can find some versions of xcode and download without authentication.

https://storage.googleapis.com/xcodes-cache/

**Comment by MattKiazyk** [comment]
PSA: Please don't download Xcode from anywhere but Apple's servers. Just search for `XcodeGhost` for some history.

**Comment by slonopotamus** [comment]
> Please don't download Xcode from anywhere but Apple's servers

If their SHA256 (or whatever) matches originals - why not?
