### ISSUE TITLE
Output more information about current step and progress in install process

### ISSUE THREAD

**Issue by interstateone** [RobotsAndPencils/xcodes#34]
Should print the following steps for the install command:

- Downloading, with progress as a percentage, if the archive is being downloaded. If installing from an archive URL, print that this is occurring as a confirmation of the use of the `--url` flag.
- Unarchiving, with a note that this can take a while. If it's possible to output some sort of indeterminate activity indicator, do that. I don't necessarily want to use PackageKit without more investigation, so that could be a separate issue if not done here.
- Moving unarchived Xcode to /Applications
- Moving archive to Trash
- Performing security/signing validation
- Enable developer mode
- Approve license
- Install components

**Comment by thii** [comment]
This can be done by using the private framework `PackageKit`. I have done a similar one here:
https://github.com/thii/Unxip/blob/1e344e3d7e9d3932d5aaa3cd9a077f21c7ef75e5/Sources/Unxip/main.swift#L26-L42

**Comment by interstateone** [comment]
Ah that's great to know, thanks @thii!

**Comment by daveanderson** [comment]
E.g.  when the .xip has been downloaded there is no indication of what is still happening

```
$ xcodes install "11.0 Beta 3"
Downloading Xcode 11.0.0-beta.3+11M362V: 100%

```

**Comment by thii** [comment]
> This can be done by using the private framework PackageKit. I have done a similar one here:
> https://github.com/thii/Unxip/blob/1e344e3d7e9d3932d5aaa3cd9a077f21c7ef75e5/Sources/Unxip/main.swift#L26-L42

On a second thought, linking with a private framework would make users unable to install `xcodes` using tools that only use the standard build command (`swift build -c release`) like Mint. What do you think about printing out something like continuous dot (`.`) after an interval to indicate that the unxipping process is still running?

**Comment by interstateone** [comment]
That's a good point. A few thoughts:

- I don't think resolving this issue necessarily requires using PackageKit. Simply a list of steps and notes if they're long running would be an improvement on the current UI. I've elaborated a bit in the PR description so the requirements are more clear. Investigating the implications of using PackageKit and possibly implementing it could be a separate issue.
- Generally, I don't have a lot of personal motivation for supporting Mint, so I don't think that should block a hypothetical feature that had clear benefits.
- Anything that indicates "indeterminate activity" would be appropriate. A sequence of dots are one option, although they may be ambiguous as to determinate vs. indeterminate progress. I've seen some tools implement spinners with ASCII or other characters, like https://github.com/sindresorhus/ora. I agree that something is better than nothing, which is the current state, though.
