### ISSUE TITLE
Support `latest` alias when installing

### ISSUE THREAD

**Issue by chriskchew** [RobotsAndPencils/xcodes#36]
It would be nice to say `xcodes install` or `xcodes install latest` in order to automatically install the latest version of XCode.

**Comment by interstateone** [comment]
@chriskchew One question I have for this addition is how to handle beta versions. One idea that came to mind was to have two options added: `xcodes install --latest` which would install the latest non-beta version and `xcodes install --latest-beta` which would install the latest beta, if any are available. Does that sound reasonable to you?

**Comment by daveanderson** [comment]
Note: with the betas you need to delete the old beta before you install the new beta or things don’t work and you have to delete both and reinstall
