### ISSUE TITLE
Xcode 11 beta

### ISSUE THREAD

**Issue by paulthorsteinson** [RobotsAndPencils/xcodes#48]
I did `xcodes update` and then `xcodes list` and I do not see the 11 beta.  I do see it when I use xcversion.  It would seem that this might be a regression as #6 implies that this was once added.

**Comment by interstateone** [comment]
Thanks Paul! This bug is due to a redesign of the download page that broke the related scraping code. I have a PR up now to address this.

**Comment by paulthorsteinson** [comment]
@interstateone Awesome, thanks!  Great work thus far :)
