### ISSUE TITLE
Different beta versions installed to the same location

### ISSUE THREAD

**Issue by thii** [RobotsAndPencils/xcodes#54]
When I installed Xcode 11 beta 2 it replaced the previously installed Xcode 11 beta 1 at `/Applications/Xcode-11.0.0-beta`. (`xcode-install` does keep each beta version separately)

It would be nice to keep the previously installed beta versions as is. The old betas are removed from the Apple website when the new beta is available, and sometimes there are new issues with the latest beta so being able to switch back would be nice (happened to us last year with Xcode 10 beta 5).

**Comment by interstateone** [comment]
Thanks for opening an issue about this @thii. I'd like to address this as part of a solution for #22 that I'm working on. I'll leave this open as a distinct ticket because it serves as a vote for _not_ replacing previous beta releases.
