### ISSUE TITLE
Ensure that error output from shell commands is printed

### ISSUE THREAD

**Issue by interstateone** [RobotsAndPencils/xcodes#65]
I've hit this a few times when the xip command is unarchiving because I've run out of disk space. xcodes currently prints that an error occurred (don't have it handy to paste here) but not the exact underlying error. The xip command does print this itself though, so xcodes probably just needs to capture standard output or standard error data and print it.

A change that resolves issue this should make sure that all shell commands have this behaviour.

**Comment by MattKiazyk** [comment]
got this same situation yesterday. Error from xcodes is below:

```
Found existing archive that will be used for installation at /Users/mattkiazyk/Library/Application Support/com.robotsandpencils.xcodes/Xcode-11.0.0.xip.
Failed executing: `/usr/bin/xip --expand "/Users/mattkiazyk/Library/Application Support/com.robotsandpencils.xcodes/Xcode-11.0.0.xip"` (1).

```
Double tapping on xip gave the out of space proper message
