### ISSUE TITLE
Apple Developer authentication has changed

### ISSUE THREAD

**Issue by interstateone** [RobotsAndPencils/xcodes#83]
At some point today (2019/11/12) Apple changed how their auth works. This involves not just a small change like the URL `https://olympus.itunes.apple.com/v1/session` to `https://appstoreconnect.apple.com/olympus/v1/session` but a larger one like where the `X-Apple-Widget-Key` header value comes from. Will need to do some more digging to find out how we can replicate it.

**Comment by davedelong** [comment]
```GET https://appstoreconnect.apple.com/olympus/v1/app/config?hostname=itunesconnect.apple.com```

**Comment by interstateone** [comment]
Ah, thanks @davedelong! I see now that that's what xcinfo is using too. I was worried I'd be in for a bunch of digging through the web inspector to figure this out.
