### ISSUE TITLE
Investigate performing downloads with aria2

### ISSUE THREAD

**Issue by interstateone** [RobotsAndPencils/xcodes#93]
- [x] Test out how much of an improvement it is on its own, if any
- [x] Prove out performing downloads with aria2. Can it work with no user-facing changes to xcodes? Assume that users are responsible for installing it separately (it's in homebrew) and xcodes will detect that and run it in a separate process.

Reference:
https://github.com/vineetchoudhary/Downloader-for-Apple-Developers
https://blog.kulman.sk/faster-way-to-download-and-install-xcode/

**Comment by achirkof** [comment]
Using **aria2** will make installation up to 5 times faster. Would be good to implement this.

**Comment by kiliankoe** [comment]
This being implemented is very cool! Can't wait for a version bump 😊

**Comment by interstateone** [comment]
https://github.com/RobotsAndPencils/xcodes/releases/tag/0.13.0 😄
