### ISSUE TITLE
Xcode.app naming convention

### ISSUE THREAD

**Issue by thii** [RobotsAndPencils/xcodes#98]
In our team, people use both this tool and `xcode-install` to install Xcode. The naming convention of the installed Xcode bundle of two is different, for example, with Xcode 11:

* `xcode-install` installs it to `/Applications/Xcode-11.app` 
* `xcodes` installs it to `/Applications/Xcode-11.0.0.app` 

I'd like to request to use the same naming convention with `xcode-install`.

Why is it important to us?

To ensure the reproducible builds, for a specific version of Xcode, everyone must have it installed to the same location. The reason being the system header paths will be embedded in the object files and archives as absolute paths (that starts with `/Applications/Xcode...`).

Alternative considered:

* We could ask everyone to only use `xcodes` or `xcode-install`, but for some reason, it has become diverse.
* We could ask everyone to rename their Xcode installations to follow one naming convention, but that would come with a cost—forgetting to rename a version means they won't get the build cache.
* We could open an issue to the `xcode-install` repo to request it to follow `xcodes`'s naming convention. We prefer using a native tool to a Ruby tool, since it has less overhead.
* Fork `xcodes` to modify it and use our own fork. This is the last thing we would want to do.

**Comment by thii** [comment]
Closing as it seems inappropriate.

**Comment by interstateone** [comment]
Hey @thii, thanks for opening this issue! I think it's worth discussing, and appreciate how you've described the problem. I've run into this a few times myself where a service like Circle CI or GitHub Actions non-self-hosted runners has Xcode installed at one path but development machines using xcodes will have it installed at another.

Personally I prefer xcodes' naming for clarity, and so the implementation can delegate to mxcl/Version, so I would probably solve this problem in a different way, but I'm biased. 😄 If there are a lot of people who chime in on this issue then it might be worth revisiting.
